name: videopred
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cudatoolkit=11.1.74
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.3.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - ncurses=6.2
  - nettle=3.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openh264=2.1.0
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pillow=8.3.1
  - pip=21.0.1
  - python=3.7.11
  - pip:
    - absl-py==0.13.0
    - blessings==1.7
    - cachetools==4.2.2
    - charset-normalizer==2.0.4
    - click==8.0.3
    - coolname==1.1.0
    - correlation-cuda==0.0.0
    - cycler==0.10.0
    - deepspeed==0.5.1
    - easydict==1.9
    - flow-vis-torch==0.1
    - forward-warp-cuda==0.0.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - gpustat==0.6.0
    - grpcio==1.39.0
    - idna==3.2
    - imageio==2.9.0
    - importlib-metadata==4.8.1
    - joblib==1.0.1
    - jsonpatch==1.32
    - jsonpointer==2.1
    - kiwisolver==1.3.2
    - lpips==0.1.4
    - markdown==3.3.4
    - matplotlib==3.4.3
    - mmdet==1.1.0+f84ec27
    - natsort==8.0.0
    - networkx==2.6.3
    - ninja==1.10.2
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - packaging==21.0
    - protobuf==3.17.3
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytorch-msssim==0.2.1
    - pytorch-ssim==0.1
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.2.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - runx==0.0.11
    - scikit-image==0.18.3
    - scikit-learn==0.24.2
    - scipy==1.1.0
    - sklearn==0.0
    - tabulate==0.8.9
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==1.8
    - threadpoolctl==2.2.0
    - tifffile==2021.8.30
    - torchfile==0.1.0
    - torchgeometry==0.1.2
    - tornado==6.1
    - tqdm==4.62.2
    - triton==1.0.0
    - urllib3==1.26.6
    - visdom==0.1.8.9
    - websocket-client==1.2.1
    - werkzeug==2.0.1
    - zipp==3.5.0
